### ISSUE TITLE
Python issue: the __init__.py is misnamed

### ISSUE THREAD

**Issue by murlock** [bbougon/crm-pilates#1]
"Thanks" for the terminal inside Live Share but I wrote `___init__.py` instead of `__init__.py`

**Comment by bbougon** [comment]
I don't think I did push this modification as I disconnected Live Share about 20 minutes ago (and I am sorry about that if I ended your connection, it wasn't my intention).
For me everything looks fine now, if you pull the main branch, you should see the las modifications I've done (mainly module tree arrangement).
Does it look good good for you?

**Comment by bbougon** [comment]
BTW, I think we should work on the CI next time

**Comment by bbougon** [comment]
closed because it was only a review of our mob session
